version: '3.3'
name: airflow
services:
  airflow:
    build:
      context: .
      dockerfile: dev_Dockerfile
    env_file:
      - 'dev_airflow_common.env'
    ports:
      - '8080:8080'
    volumes:
      - ../dags:/usr/local/airflow/dags
      - ../logs:/usr/local/airflow/logs
      - ./scripts:/usr/local/airflow/scripts
      - ./dev_airflow.cfg:/usr/local/airflow/airflow.cfg
    command: bash -c "/usr/local/airflow/scripts/start.sh"

  postgres:
    image: postgres:13
    env_file:
      - 'dev_postgres_common.env'

  broker:
    image: redis:latest
    env_file:
      - 'dev_redis_common.env'
    volumes:
      - ./dev_redis.conf:/etc/redis/conf/redis.conf

#docker-compose up --build
#docker-compose down --volumes --remove-orphans

## delete
# sudo docker system prune -a
